### ISSUE TITLE
this is not a plugin

### ISSUE THREAD

**Issue by nobodyatandnothing** [michaelb/do-nothing.vim#11]
no code is loaded.
it is not 'a plugin that does nothing'. it is 'not a plugin' 
i was disappointed when i found that do-nothing.vim was empty

**Comment by michaelb** [comment]
Actually, a source file containing valid Vimscript is sourced (it just happens it's empty)

With the backing of the vimscript engine, I can say that not only the executed code is correct, but is arguably better than "non-empty" code that would by nature, introduce side effects, slow down the plugin, and increase complexity for no benefit
