### ISSUE TITLE
Fix documented code coverage

### ISSUE THREAD

**Issue by spenserblack** [michaelb/do-nothing.vim#8]
The README reports 100% code coverage. However, with 0 lines, and 0 covered lines, it's more like 0/0 code coverage. Assuming that the number of lines is a constant, but covered lines is variable, than coverage = :infinity:% for `covered lines` :arrow_right: 0, where `covered lines` cannot be less than 0.

I'm not enough of a math whiz to be an authority, but I think you can claim infinite code coverage (:tada:).

**Comment by michaelb** [comment]
As anything greater than 100% coverage makes absolutely no sense, I'm afraid I will have to leave this as-is.

My reasoning was that as every line of code is covered (which is true), the code coverage is equal to 100%
